name: Auditoría de Patrimonio (Manual)

on:
  workflow_dispatch: # Esto habilita el botón manual "Run workflow"
  schedule:
    # Se ejecuta automáticamente todos los domingos a las 8:00 PM (Hora CDMX aprox)
    - cron: '0 2 * * 1' 

jobs:
  check_wealth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: |
          pip install yfinance requests pandas

      - name: Ejecutar Auditoría
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python patrimonio.py
